### ISSUE TITLE
justifying text

### ISSUE THREAD

**Issue by krbaehrle** [brrd/Abricotine#169]
[Probably enhancement]
I tried to change my theme in a way that paragraphs will be justified and could not figure out a solution for it. I think the way the content is structured now using nested `<span>` does not allow justifying. Right or wrong?

**Comment by brrd** [comment]
Try:
```less
.CodeMirror-wrap pre {
	text-align: justify;
}
```
at the end of your theme.less.
