### ISSUE TITLE
[Question] Modify theme.less: automatically change color/size of text for second level of an unordered list / modify line height / remove padding/margin

### ISSUE THREAD

**Issue by jrgzdzekln** [brrd/abricotine#309]
Hello! Abricotine is so cool! Thank you.

1/ How to modify the theme.less file to automatically make the second level of an unordered list of a different size and color?
```
- white text of size 14
        - blue text of size 9
        - blue text of size 9
- white text of size 14
```
2/ How modify the theme.less file to reduce the line height to the minimum for the whole file (text, lists)?
3/ How to modify the theme.less to remove all the padding/margin of the whole file?

I could not find a way, despite my researches in LESS documentation and internet.
I am not a coder.

**Comment by brrd** [comment]
> 1/ How to modify the theme.less file to automatically make the second level of an unordered list of a different size and color?

You can't do this, sorry.

> 2/ How modify the theme.less file to reduce the line height to the minimum for the whole file (text, lists)?

```less
.CodeMirror pre.CodeMirror-line, .CodeMirror pre.CodeMirror-line-like {
    line-height: 1;
}
```

>  3/ How to modify the theme.less to remove all the padding/margin of the whole file?

```less
.CodeMirror-sizer {
    width: auto;
    max-width: none;
}
```

Abricotine uses CodeMirror under the hood, which is not really designed to be customized like this. Be aware you may run into bugs when tweaking this much.
